import { createElement } from 'lwc';
import Wgc_attivita_odierne from 'c/wgc_attivita_odierne';

describe('c-wgc-attivita-odierne', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-wgc-attivita-odierne', {
            is: Wgc_attivita_odierne
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});